# Generated by Django 4.0.1 on 2022-01-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=10)),
                ('start', models.CharField(max_length=250)),
                ('finish', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('seats', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=150)),
                ('seat', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('departure', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Awaiting departure', 'Awaiting departure'), ('Journey complete', 'Journey complete'), ('Cancelled', 'Cancelled')], default='Awaiting departure', max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bus')),
            ],
        ),
    ]
